services:
  mariadb:
    image: mariadb:latest
    environment:
       MARIADB_DATABASE: gestational
       MARIADB_PASSWORD: erick
       MARIADB_ROOT_PASSWORD: erick
       MARIADB_USER: erick
    ports:
      - '3306:3306'
